# [START swagger]
swagger: '2.0'
info:
  description: Order Microservice
  title: Order Microservice
  version: 1.0.0
host: order-ms-227100.appspot.com
# [END swagger]
consumes:
  - application/json
produces:
  - application/json
  - application/xml
schemes:
  - https
  - http
paths:
  /api:
    get:
      tags:
        - api
      description: Returns a default api message
      operationId: getApi
      security:
        - api_key: []
      produces:
        - application/json
      responses:
        200:
          description: successful operation
  /store/inventory:
    get:
      tags:
        - store
      summary: Returns user inventories from the store
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        200:
          description: successful operation
      security:
        - api_key: []
  /store/orders:
    post:
      tags:
        - store
      summary: Place an order for a user
      operationId: addOrder
      produces:
        - 'application/json'
      responses:
        201:
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        400:
          description: Invalid Order
      security:
        - api_key: []
      parameters:
        - description: Order information
          in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/Order'
  /store/orders/{orderId}:
    get:
      tags:
        - store
      summary: Find purchase order by ID
      operationId: getOrder
      produces:
        - 'application/json'
        - 'application/xml'
      responses:
        201:
          description: successful operation
          schema:
            $ref: '#/definitions/Order'
        400:
          description: Invalid ID supplied
        404:
          description: Order not found
      security:
        - api_key: []
      parameters:
        - in: path
          name: orderId
          type: integer
          required: true
          description: Numeric ID of the order to get.
    delete:
      tags:
        - store
      summary: Deletes the order with the specified ID.
      operationId: removeOrder
      responses:
        204:
          description: User was deleted.
        400:
          description: Invalid ID supplied
        404:
          description: Order not found
      security:
        - api_key: []
      parameters:
        - in: path
          name: orderId
          type: integer
          required: true
          description: Numeric ID of the order to get.
definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          - placed
          - approved
          - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order
# This section requires all requests to any path to require an API key.
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: 'apiKey'
    name: 'key'
    in: 'query'
